- hosts: all
  tasks:
    - name: install vsftpd
      yum:
        name: vsftpd
        state: installed



    - name: install httpd
      copy:
         content: "hello"
         dest: abc.txt
     
  
